### ISSUE TITLE
IMA parallel not working 

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/IMA#1531]
**Preconditions** 
IMA Agent: 2.0.0-beta.5 

**To Reproduce**
Run IMA Agent 
Observe logs 

**Expected behavior**
IMA parallel works properly 

**Actual result** 
IMA parallel search failed and skip, was started previous algorithm(s
[imaPar.txt](https://github.com/skalenetwork/IMA/files/12030899/imaPar.txt)
equential search)

**Comment by sergiy-skalelabs** [comment]
This task is not about parallel IMA message streams. It's about SKALE Network Browser (SNB) unable to fecth connected chains to this S-Chain from SKALE Manager smart contracts behind Main Net node running by validator. If SNB cannot fetch connected chains then S2S transfers will not be preformed until list of conneted chains fetched later.

**Comment by EvgeniyZZ** [comment]
Parallel requests not working with infura url.

**Comment by yatsunastya** [comment]
The issue is reproduced with working geth node (load balancer) 
`2023-07-25 11:47:13.532: Failed to start parallel periodic SNB refresh, error is: timeout of 60 reached, will restart periodic SNB refresh in non-parallel mode`
[non-parallel.txt](https://github.com/skalenetwork/IMA/files/12160894/non-parallel.txt)

**Comment by EvgeniyZZ** [comment]
Related to https://github.com/skalenetwork/IMA/issues/1467

**Comment by EvgeniyZZ** [comment]
Verified: Agent worked several days without any time/preference gaps
IMA Agent: 2.0.0-beta.17
